### ISSUE TITLE
東京版で削除されたページが未だに残っている

### ISSUE THREAD

**Issue by azurata45** [Code-for-OKINAWA/covid19#155]
## 起こっている問題 / The Problem
- 東京版で削除されたページ「東京都23区の人口推移（参考値）」が未だに残っている

## スクリーンショット / Screenshot
![okinawa stopcovid19 jp_largemap_](https://user-images.githubusercontent.com/31302074/78576551-ca58c000-7867-11ea-8273-403a24d1a8d7.png)

## 期待する見せ方・挙動 / Expected Behavior
- 該当ページの削除

## 起こっている問題の再現手段 / Steps to Reproduce
[こちら](https://okinawa.stopcovid19.jp/largemap/)からアクセスできます

**Comment by masakifujie** [comment]
指摘ありがとうございます。もし可能であればプルリクも上げていただけないでしょうか？

**Comment by azurata45** [comment]
了解です

**Comment by amouro** [comment]
Since we are going to remove the page, do we also want to clean the related components?

https://github.com/Code-for-OKINAWA/covid19/blob/5cfca51c424bf2c93b9c9fa20b2ec6423b2e4f36/pages/largemap.vue#L18
https://github.com/Code-for-OKINAWA/covid19/blob/5cfca51c424bf2c93b9c9fa20b2ec6423b2e4f36/components/cards/TokyoCityMapCard.vue#L26
https://github.com/Code-for-OKINAWA/covid19/blob/5cfca51c424bf2c93b9c9fa20b2ec6423b2e4f36/components/MapCard.vue#L67-L69

**Comment by azurata45** [comment]
Yes we do. These not used by other pages. I will delete these. Thank you for advice me.

**Comment by azurata45** [comment]
Now, I checked ran without these components, the server don't work.
I will search the cause, so I delete the request.

**Comment by azurata45** [comment]
MapCard.vue is used by some components included by index.vue. But, these are not used. So, we should new issue about non used components included index.vue
